# Generated by Django 2.1.3 on 2018-12-07 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20181207_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2018)]),
        ),
    ]
